language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ccolonri/docker-react -f Dockerfile.dev . 


script:
  - docker run -e CI=true ccolonri/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker2"
  env: "Docker2-env"
  bucket_name: "elasticbeanstalk-us-east-2-963382967277"
  bucket_path: "docker2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
